version: 0.2

phases:
 
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - apt update
      - sleep 15
     
      - apt install docker-ce
      - sudo systemctl status docker




      - sleep 120
  build:
    commands:
      - echo  $(docker --version)
      - echo $(aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 353641719040.dkr.ecr.eu-central-1.amazonaws.com)
      - echo $(docker build  -t 353641719040.dkr.ecr.eu-central-1.amazonaws.com/test:1245 .)
      -  echo $(docker push 353641719040.dkr.ecr.eu-central-1.amazonaws.com/test:1245 )
      - echo Build started on `date`
